directories:
  output: release
  buildResources: build
appId: com.dineflow.app
productName: DineFlow
files:
  - filter:
      - dist/**/*
      - electron/**/*
mac:
  category: public.app-category.business
win:
  target: nsis
linux:
  target: AppImage
electronVersion: 24.8.8
